Updated README, added validation of CDK strat and removed always() from each CDK strat

diff --git a/.github/workflows/aws-cdk.yml b/.github/workflows/aws-cdk.yml
--- a/.github/workflows/aws-cdk.yml
+++ b/.github/workflows/aws-cdk.yml
@@ -168,6 +168,14 @@ jobs:
               exit 1
             fi
           fi
+
+          # Valide that one synth, diff or deploy boolean is true
+          if [ "${{ inputs.synth }}" ] || [ "${{ inputs.synth }}" ] || [ "${{ inputs.synth }}" ]; then
+            continue
+          else
+            echo "❌ Error: No CDK commands have been set"
+            exit 1
+          fi
           
           echo "✅ All inputs validated successfully"
 
@@ -265,7 +273,7 @@ jobs:
     name: 🔨 CDK Synthesis
     runs-on: ubuntu-latest
     needs: [setup-node, prepare, bootstrap]
-    if: always() && (needs.prepare.result == 'success' && (needs.bootstrap.result == 'success' || needs.bootstrap.result == 'skipped')) && inputs.synth == 'true'
+    if: (needs.prepare.result == 'success' && (needs.bootstrap.result == 'success' || needs.bootstrap.result == 'skipped')) && inputs.synth == 'true'
     outputs:
       sanitised-cdk-stack-name: ${{ steps.sanitise.outputs.sanitised-cdk-stack-name }}
     steps:
@@ -344,7 +352,7 @@ jobs:
     name: 📊 CDK Diff
     runs-on: ubuntu-latest
     needs: [setup-node, prepare, synth]
-    if: always() && needs.synth.result == 'success' && inputs.diff == 'true'
+    if: needs.synth.result == 'success' && inputs.diff == 'true'
     outputs:
       has-changes: ${{ steps.diff-analysis.outputs.has-changes }}
       diff-summary: ${{ steps.diff-analysis.outputs.summary }}
